# set true color, apparently is not required by iterm2
set-option -sa terminal-overrides ",xterm*:Tc"

# Capture mouse
set -g mouse on

# Start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Open panes in current directory
bind '"' split-window -h -c "#{pane_current_path}"
bind % split-window -v -c "#{pane_current_path}"

# set prefix from <C-b> to <C-space>
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Shift alt h/l to switch between windows
bind -n Ó previous-window
bind -n Ò next-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'mocha' # latte, frappe, macchiato, mocha
set -g @catppuccin_l_right_separator "█"
set -g @catppuccin_r_left_separator "█"
set -g @catppuccin_date_time "%d-%m-%Y %H:%M"

run '~/.tmux/plugins/tpm/tpm'
